-- MySQL Script generated by MySQL Workbench
-- 09/19/15 15:00:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `idproducto` INT NOT NULL,
  `tipo` VARCHAR(100) NULL,
  `descripcion` VARCHAR(100) NULL,
  `unidadmedida` INT NULL,
  `precio` DECIMAL(10,2) NULL,
  `idusuario` VARCHAR(45) NULL,
  PRIMARY KEY (`idproducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comida` (
  `idcomida` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(100) NULL,
  `idusuario` VARCHAR(45) NULL,
  PRIMARY KEY (`idcomida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ComidaProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ComidaProducto` (
  `id` INT NOT NULL,
  `Producto_idproducto` INT NOT NULL,
  `Comida_idcomida` INT NOT NULL,
  `idusuario` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ComidaProducto_Producto1_idx` (`Producto_idproducto` ASC),
  INDEX `fk_ComidaProducto_Comida1_idx` (`Comida_idcomida` ASC),
  CONSTRAINT `fk_ComidaProducto_Producto1`
    FOREIGN KEY (`Producto_idproducto`)
    REFERENCES `mydb`.`Producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ComidaProducto_Comida1`
    FOREIGN KEY (`Comida_idcomida`)
    REFERENCES `mydb`.`Comida` (`idcomida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `apellidos` VARCHAR(100) NULL,
  `correo` VARCHAR(50) NULL,
  `` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actividad` (
  `idActividad` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `fechacreacion` DATETIME NULL,
  `fecharealizado` VARCHAR(45) NULL,
  `idusuario` VARCHAR(45) NULL,
  PRIMARY KEY (`idActividad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Presupuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Presupuesto` (
  `idPresupuesto` INT NOT NULL,
  `Presupuestocol` VARCHAR(45) NULL,
  `idusuario` VARCHAR(45) NULL,
  PRIMARY KEY (`idPresupuesto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PresupuestoDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PresupuestoDetalle` (
  `idproducto` INT NOT NULL,
  `idPresupuesto` INT NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL,
  `idusuario` VARCHAR(45) NULL,
  INDEX `fk_PresupuestoDetalle_Producto1_idx` (`idproducto` ASC),
  INDEX `fk_PresupuestoDetalle_Presupuesto1_idx` (`idPresupuesto` ASC),
  PRIMARY KEY (`cantidad`),
  CONSTRAINT `fk_PresupuestoDetalle_Producto1`
    FOREIGN KEY (`idproducto`)
    REFERENCES `mydb`.`Producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PresupuestoDetalle_Presupuesto1`
    FOREIGN KEY (`idPresupuesto`)
    REFERENCES `mydb`.`Presupuesto` (`idPresupuesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agenda` (
  `idAgenda` INT NOT NULL,
  `idusuario` VARCHAR(45) NULL,
  PRIMARY KEY (`idAgenda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalleactividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalleactividad` (
  `iddetalleactividad` INT NOT NULL,
  `Agenda_idAgenda` INT NOT NULL,
  `Actividad_idActividad` INT NOT NULL,
  `idusuario` VARCHAR(45) NULL,
  PRIMARY KEY (`iddetalleactividad`),
  INDEX `fk_detalleactividad_Agenda1_idx` (`Agenda_idAgenda` ASC),
  INDEX `fk_detalleactividad_Actividad1_idx` (`Actividad_idActividad` ASC),
  CONSTRAINT `fk_detalleactividad_Agenda1`
    FOREIGN KEY (`Agenda_idAgenda`)
    REFERENCES `mydb`.`Agenda` (`idAgenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalleactividad_Actividad1`
    FOREIGN KEY (`Actividad_idActividad`)
    REFERENCES `mydb`.`Actividad` (`idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
